<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API.Core\API.Core.csproj" />
    <ProjectReference Include="..\API.Users\API.Users.csproj" />
    <ProjectReference Include="..\API.PaymentMethods\API.PaymentMethods.csproj" />
    <ProjectReference Include="..\API.Transactions\API.Transactions.csproj" />
    <ProjectReference Include="..\API.Categories\API.Categories.csproj" />
    <ProjectReference Include="..\API.Goals\API.Goals.csproj" />
    <ProjectReference Include="..\API.Notifications\API.Notifications.csproj" />
    <ProjectReference Include="..\API.FixedIncomes\API.FixedIncomes.csproj" />
  </ItemGroup>

</Project>
